import type { ConnectorSpec } from "../base/types";
import { declarative, scaffold } from "./spec";

/**
 * Moda europea/global fuera de Inditex y H&M Group: marcas propias (DTC), retail
 * británico y los grandes pure players. Los pure players (ASOS, Zalando, About
 * You, Boohoo, PLT) NO se scrapean: su vía legítima es feed de afiliación o API
 * de partner, y así queda declarado.
 */

export const EUROPE_SOURCES: ConnectorSpec[] = [
  declarative({
    id: "uniqlo",
    label: "UNIQLO",
    brand: "UNIQLO",
    group: "Fast Retailing",
    homeUrl: "https://www.uniqlo.com/es/es/",
    sitemapUrls: ["https://www.uniqlo.com/es/sitemap.xml"],
    productUrlPattern: String.raw`uniqlo\.com\/.+\/products\/E\d{6,}`,
    productIdPattern: String.raw`\/products\/(E\d{6,})`,
    segments: ["women", "men", "kids"],
    categories: ["clothing", "accessories"],
    notes:
      "Catálogo con JSON-LD y API pública de producto por id (E<id>). Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "na-kd",
    label: "NA-KD",
    brand: "NA-KD",
    homeUrl: "https://www.na-kd.com/es",
    sitemapUrls: ["https://www.na-kd.com/sitemap.xml"],
    productUrlPattern: String.raw`na-kd\.com\/.+\/[a-z0-9-]+-\d{6,}`,
    productIdPattern: String.raw`-(\d{6,})`,
    markets: ["ES", "EU"],
    segments: ["women"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "c-and-a",
    label: "C&A",
    brand: "C&A",
    homeUrl: "https://www.c-and-a.com/es/es/shop",
    sitemapUrls: ["https://www.c-and-a.com/sitemap.xml"],
    productUrlPattern: String.raw`c-and-a\.com\/.+\/p\/\d{6,}`,
    productIdPattern: String.raw`\/p\/(\d{6,})`,
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "reiss",
    label: "Reiss",
    brand: "Reiss",
    homeUrl: "https://www.reiss.com/es/",
    sitemapUrls: ["https://www.reiss.com/sitemap.xml"],
    productUrlPattern: String.raw`reiss\.com\/.+\/style\/\w+`,
    productIdPattern: String.raw`\/style\/(\w+)`,
    tier: "premium",
    markets: ["UK", "ES"],
    region: "UK",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "river-island",
    label: "River Island",
    brand: "River Island",
    homeUrl: "https://www.riverisland.com/",
    sitemapUrls: ["https://www.riverisland.com/sitemap.xml"],
    productUrlPattern: String.raw`riverisland\.com\/p\/[a-z0-9-]+-\d{6,}`,
    productIdPattern: String.raw`-(\d{6,})`,
    region: "UK",
    markets: ["UK"],
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "levis",
    label: "Levi's",
    brand: "Levi's",
    group: "Levi Strauss & Co.",
    homeUrl: "https://www.levi.com/ES/es_ES/",
    sitemapUrls: ["https://www.levi.com/sitemap.xml"],
    productUrlPattern: String.raw`levi\.com\/.+\/p\/[\w-]+`,
    productIdPattern: String.raw`\/p\/([\w-]+)`,
    tier: "premium",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "tommy-hilfiger",
    label: "Tommy Hilfiger",
    brand: "Tommy Hilfiger",
    group: "PVH",
    homeUrl: "https://es.tommy.com/",
    sitemapUrls: ["https://es.tommy.com/sitemap.xml"],
    productUrlPattern: String.raw`tommy\.com\/.+\/[\w-]+-\w{6,}\.html`,
    productIdPattern: String.raw`-(\w{6,})\.html`,
    tier: "premium",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "calvin-klein",
    label: "Calvin Klein",
    brand: "Calvin Klein",
    group: "PVH",
    homeUrl: "https://www.calvinklein.es/",
    sitemapUrls: ["https://www.calvinklein.es/sitemap.xml"],
    productUrlPattern: String.raw`calvinklein\.es\/.+\/[\w-]+-\w{6,}\.html`,
    productIdPattern: String.raw`-(\w{6,})\.html`,
    tier: "premium",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories", "lingerie"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "lacoste",
    label: "Lacoste",
    brand: "Lacoste",
    homeUrl: "https://www.lacoste.com/es/",
    sitemapUrls: ["https://www.lacoste.com/sitemap.xml"],
    productUrlPattern: String.raw`lacoste\.com\/.+\/[\w-]+\.html`,
    productIdPattern: String.raw`\/(\w{6,})\.html`,
    tier: "premium",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "guess",
    label: "GUESS",
    brand: "GUESS",
    homeUrl: "https://www.guess.eu/es_ES/",
    sitemapUrls: ["https://www.guess.eu/sitemap.xml"],
    productUrlPattern: String.raw`guess\.eu\/.+\/p\/[\w-]+`,
    productIdPattern: String.raw`\/p\/([\w-]+)`,
    tier: "premium",
    segments: ["women", "men"],
    categories: ["clothing", "bags", "watches", "footwear"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "diesel",
    label: "Diesel",
    brand: "Diesel",
    group: "OTB",
    homeUrl: "https://es.diesel.com/es/",
    sitemapUrls: ["https://es.diesel.com/sitemap.xml"],
    productUrlPattern: String.raw`diesel\.com\/.+\/[\w-]+\/[A-Z0-9]{6,}`,
    productIdPattern: String.raw`\/([A-Z0-9]{6,})`,
    tier: "premium",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "superdry",
    label: "Superdry",
    brand: "Superdry",
    homeUrl: "https://www.superdry.es/",
    sitemapUrls: ["https://www.superdry.es/sitemap.xml"],
    productUrlPattern: String.raw`superdry\.es\/.+\/p\/[\w-]+`,
    productIdPattern: String.raw`\/p\/([\w-]+)`,
    region: "UK",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),

  /* ---------------- pure players: nunca por scraping ---------------- */

  scaffold({
    id: "asos",
    label: "ASOS",
    brand: "ASOS",
    homeUrl: "https://www.asos.com/es/",
    productUrlPattern: String.raw`asos\.com\/.+\/prd\/\d+`,
    productIdPattern: String.raw`\/prd\/(\d+)`,
    tier: "marketplace",
    region: "UK",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    access: "affiliate_feed",
    compliance: "affiliate_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["ASOS_AFFILIATE_FEED_URL"],
    notes:
      "ASOS no publica JSON-LD Product completo y su catálogo va por API interna cuyo uso no está autorizado. Vía legítima: feed de producto de su programa de afiliación (Awin). Con la credencial en ASOS_AFFILIATE_FEED_URL el conector pasa a implementarse contra el feed, nunca contra la web.",
    docsUrl: "https://www.awin.com/",
  }),
  scaffold({
    id: "zalando",
    label: "Zalando",
    brand: "Zalando",
    homeUrl: "https://www.zalando.es/",
    productUrlPattern: String.raw`zalando\.[a-z.]+\/.+\.html`,
    productIdPattern: String.raw`([A-Z0-9]{2}\d{3}[A-Z0-9]+)\.html`,
    tier: "marketplace",
    region: "DE",
    markets: ["ES", "DE", "EU"],
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "accessories"],
    access: "partner_api",
    compliance: "partner_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["ZALANDO_PARTNER_CLIENT_ID", "ZALANDO_PARTNER_CLIENT_SECRET"],
    notes:
      "Challenge anti-bot agresivo: el scraping queda descartado. Vía legítima: Zalando Partner API (requiere contrato y credenciales OAuth).",
    docsUrl: "https://partner.zalando.com/",
  }),
  scaffold({
    id: "about-you",
    label: "ABOUT YOU",
    brand: "ABOUT YOU",
    homeUrl: "https://www.aboutyou.es/",
    productUrlPattern: String.raw`aboutyou\.[a-z.]+\/p\/[\w-]+\/\d+`,
    productIdPattern: String.raw`\/(\d+)$`,
    tier: "marketplace",
    region: "DE",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    access: "partner_api",
    compliance: "partner_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["ABOUTYOU_PARTNER_TOKEN"],
    notes:
      "Vía legítima: SCAYLE/ABOUT YOU Partner API o feed de afiliación. Pendiente de acuerdo comercial.",
    docsUrl: "https://www.aboutyou-group.com/",
  }),
  scaffold({
    id: "boohoo",
    label: "boohoo",
    brand: "boohoo",
    homeUrl: "https://www.boohoo.com/",
    productUrlPattern: String.raw`boohoo\.com\/.+\/\w{3,}\.html`,
    productIdPattern: String.raw`\/(\w+)\.html`,
    region: "UK",
    markets: ["UK"],
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    access: "affiliate_feed",
    compliance: "affiliate_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["BOOHOO_AFFILIATE_FEED_URL"],
    notes: "Vía legítima: feed de afiliación (Awin). Pendiente de alta aprobada.",
    docsUrl: "https://www.awin.com/",
  }),
  scaffold({
    id: "prettylittlething",
    label: "PrettyLittleThing",
    brand: "PrettyLittleThing",
    homeUrl: "https://www.prettylittlething.es/",
    productUrlPattern: String.raw`prettylittlething\.[a-z.]+\/.+\.html`,
    productIdPattern: String.raw`\/(\w+)\.html`,
    region: "UK",
    segments: ["women"],
    categories: ["clothing", "footwear", "accessories"],
    access: "affiliate_feed",
    compliance: "affiliate_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["PLT_AFFILIATE_FEED_URL"],
    notes: "Vía legítima: feed de afiliación (Awin). Pendiente de alta aprobada.",
    docsUrl: "https://www.awin.com/",
  }),
  scaffold({
    id: "next",
    label: "Next",
    brand: "Next",
    homeUrl: "https://www.next.es/",
    productUrlPattern: String.raw`next\.[a-z.]+\/.+\/[a-z0-9]+-\d+`,
    productIdPattern: String.raw`-(\d+)$`,
    region: "UK",
    tier: "department_store",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "home"],
    access: "affiliate_feed",
    compliance: "affiliate_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["NEXT_AFFILIATE_FEED_URL"],
    notes: "Vía legítima: feed de afiliación. Pendiente de alta aprobada.",
    docsUrl: "https://www.awin.com/",
  }),
];
