import type { ConnectorSpec } from "../base/types";
import { declarative, scaffold } from "./spec";

/**
 * Premium, lujo y marketplaces de lujo.
 *
 * Casi todos son marketplaces con contrato: su catálogo NO se scrapea, se
 * consume por API de partner o feed de afiliación. Quedan registrados como
 * `partner_required` para que el roadmap comercial sea visible en el admin y
 * para que nadie active por error una ingesta que no está permitida.
 */

export const PREMIUM_SOURCES: ConnectorSpec[] = [
  declarative({
    id: "hugo-boss",
    label: "HUGO BOSS",
    brand: "HUGO BOSS",
    homeUrl: "https://www.hugoboss.com/es/",
    sitemapUrls: ["https://www.hugoboss.com/sitemap.xml"],
    productUrlPattern: String.raw`hugoboss\.com\/.+\/hbeu\d{8,}[_-]?\d*\.html`,
    productIdPattern: String.raw`(hbeu\d{8,})`,
    tier: "luxury",
    markets: ["ES", "EU"],
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    notes:
      "Publica JSON-LD en ficha. Patrón de ficha derivado de la estructura pública de URLs; sin verificar contra la tienda.",
  }),
  declarative({
    id: "gant",
    label: "GANT",
    brand: "GANT",
    homeUrl: "https://es.gant.com/",
    sitemapUrls: ["https://es.gant.com/sitemap.xml"],
    productUrlPattern: String.raw`gant\.es\/p\/.+\/\d{5,8}-\d{1,4}([?#]|$)`,
    productIdPattern: String.raw`gant\.es\/p\/.+\/(\d{5,8}-\d{1,4})([?#]|$)`,
    tier: "premium",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "sandro",
    label: "Sandro",
    brand: "Sandro",
    group: "SMCP",
    homeUrl: "https://es.sandro-paris.com/",
    sitemapUrls: ["https://es.sandro-paris.com/sitemap.xml"],
    productUrlPattern: String.raw`sandro-paris\.com\/.+\/p\/.+\/[A-Za-z]{4,6}\d{5}_\d{2,4}\.html([?#]|$)`,
    productIdPattern: String.raw`sandro-paris\.com\/.+\/([A-Za-z]{4,6}\d{5}_\d{2,4})\.html`,
    tier: "luxury",
    region: "FR",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "maje",
    label: "Maje",
    brand: "Maje",
    group: "SMCP",
    homeUrl: "https://es.maje.com/",
    sitemapUrls: ["https://es.maje.com/sitemap.xml"],
    productUrlPattern: String.raw`maje\.com\/.+\/p\/.+\/[A-Za-z]{4,6}\d{5}_\d{2,4}\.html([?#]|$)`,
    productIdPattern: String.raw`maje\.com\/.+\/([A-Za-z]{4,6}\d{5}_\d{2,4})\.html`,
    tier: "luxury",
    region: "FR",
    segments: ["women"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "ba-and-sh",
    label: "ba&sh",
    brand: "ba&sh",
    homeUrl: "https://ba-sh.com/es/",
    sitemapUrls: ["https://ba-sh.com/sitemap.xml"],
    productUrlPattern: String.raw`ba-sh\.com\/.+\/p\/[A-Za-z][A-Za-z_-]*-\d{13}\.html([?#]|$)`,
    productIdPattern: String.raw`ba-sh\.com\/.+-(\d{13})\.html`,
    tier: "luxury",
    region: "FR",
    segments: ["women"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),

  /* ------------- marketplaces de lujo: solo por contrato ------------- */

  scaffold({
    id: "farfetch",
    label: "Farfetch",
    brand: "Farfetch",
    homeUrl: "https://www.farfetch.com/es/",
    productUrlPattern: String.raw`farfetch\.com\/.+\/item-(\d+)\.aspx`,
    productIdPattern: String.raw`item-(\d+)\.aspx`,
    tier: "luxury",
    region: "GLOBAL",
    markets: ["ES", "EU", "GLOBAL"],
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "bags", "accessories", "jewelry"],
    access: "partner_api",
    compliance: "partner_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["FARFETCH_API_KEY", "FARFETCH_API_SECRET"],
    notes:
      "Marketplace de lujo con API de partner documentada (Farfetch Marketplace API) y programa de afiliación. Requiere contrato: sin credenciales no se ingiere nada.",
    docsUrl: "https://developers.farfetch.com/",
  }),
  scaffold({
    id: "ssense",
    label: "SSENSE",
    brand: "SSENSE",
    homeUrl: "https://www.ssense.com/es-es",
    productUrlPattern: String.raw`ssense\.com\/.+\/\d{6,}`,
    productIdPattern: String.raw`\/(\d{6,})`,
    tier: "luxury",
    region: "GLOBAL",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "bags", "accessories"],
    access: "affiliate_feed",
    compliance: "affiliate_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["SSENSE_AFFILIATE_FEED_URL"],
    notes:
      "Bloqueo anti-bot estricto. Vía legítima: feed de producto vía red de afiliación (Rakuten). Pendiente de alta.",
    docsUrl: "https://rakutenadvertising.com/",
  }),
  scaffold({
    id: "net-a-porter",
    label: "NET-A-PORTER",
    brand: "NET-A-PORTER",
    group: "YNAP",
    homeUrl: "https://www.net-a-porter.com/es-es/",
    productUrlPattern: String.raw`net-a-porter\.com\/.+\/(\d{6,})`,
    productIdPattern: String.raw`\/(\d{6,})`,
    tier: "luxury",
    region: "GLOBAL",
    segments: ["women"],
    categories: ["clothing", "footwear", "bags", "accessories", "jewelry"],
    access: "partner_api",
    compliance: "partner_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["YNAP_PARTNER_TOKEN"],
    notes:
      "Grupo YNAP: catálogo accesible solo por acuerdo de partner o red de afiliación. Pendiente de acuerdo comercial.",
    docsUrl: "https://www.ynap.com/",
  }),
  scaffold({
    id: "mr-porter",
    label: "MR PORTER",
    brand: "MR PORTER",
    group: "YNAP",
    homeUrl: "https://www.mrporter.com/es-es/",
    productUrlPattern: String.raw`mrporter\.com\/.+\/(\d{6,})`,
    productIdPattern: String.raw`\/(\d{6,})`,
    tier: "luxury",
    region: "GLOBAL",
    segments: ["men"],
    categories: ["clothing", "footwear", "bags", "accessories", "watches"],
    access: "partner_api",
    compliance: "partner_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["YNAP_PARTNER_TOKEN"],
    notes:
      "Grupo YNAP (mismo acuerdo que NET-A-PORTER). Pendiente de acuerdo comercial.",
    docsUrl: "https://www.ynap.com/",
  }),
  scaffold({
    id: "mytheresa",
    label: "Mytheresa",
    brand: "Mytheresa",
    homeUrl: "https://www.mytheresa.com/es/es/",
    productUrlPattern: String.raw`mytheresa\.com\/.+\/[\w-]+-p(\d{6,})`,
    productIdPattern: String.raw`-p(\d{6,})`,
    tier: "luxury",
    region: "DE",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "bags", "accessories"],
    access: "affiliate_feed",
    compliance: "affiliate_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["MYTHERESA_AFFILIATE_FEED_URL"],
    notes: "Vía legítima: feed de afiliación. Pendiente de alta aprobada.",
    docsUrl: "https://rakutenadvertising.com/",
  }),
  scaffold({
    id: "luisaviaroma",
    label: "LUISAVIAROMA",
    brand: "LUISAVIAROMA",
    homeUrl: "https://www.luisaviaroma.com/es-es/",
    productUrlPattern: String.raw`luisaviaroma\.com\/.+\/(\d{6,})`,
    productIdPattern: String.raw`\/(\d{6,})`,
    tier: "luxury",
    region: "IT",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "bags", "accessories"],
    access: "affiliate_feed",
    compliance: "affiliate_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["LVR_AFFILIATE_FEED_URL"],
    notes: "Vía legítima: feed de afiliación. Pendiente de alta aprobada.",
    docsUrl: "https://rakutenadvertising.com/",
  }),
  scaffold({
    id: "revolve",
    label: "REVOLVE",
    brand: "REVOLVE",
    homeUrl: "https://www.revolve.com/",
    productUrlPattern: String.raw`revolve\.com\/.+\/dp\/([\w-]+)`,
    productIdPattern: String.raw`\/dp\/([\w-]+)`,
    tier: "premium",
    region: "US",
    markets: ["US", "GLOBAL"],
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "bags", "accessories"],
    access: "affiliate_feed",
    compliance: "affiliate_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["REVOLVE_AFFILIATE_FEED_URL"],
    notes: "Vía legítima: feed de afiliación propio. Pendiente de alta aprobada.",
    docsUrl: "https://www.revolve.com/content/affiliate",
  }),
  scaffold({
    id: "end-clothing",
    label: "END. Clothing",
    brand: "END.",
    homeUrl: "https://www.endclothing.com/es/",
    productUrlPattern: String.raw`endclothing\.com\/.+\/([\w-]+)\.html`,
    productIdPattern: String.raw`\/([\w-]+)\.html`,
    tier: "premium",
    region: "UK",
    segments: ["men", "women"],
    categories: ["clothing", "footwear", "accessories"],
    access: "affiliate_feed",
    compliance: "affiliate_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["END_AFFILIATE_FEED_URL"],
    notes: "Vía legítima: feed de afiliación. Pendiente de alta aprobada.",
    docsUrl: "https://www.awin.com/",
  }),
  scaffold({
    id: "yoox",
    label: "YOOX",
    brand: "YOOX",
    group: "YNAP",
    homeUrl: "https://www.yoox.com/es/",
    productUrlPattern: String.raw`yoox\.com\/.+\/item\?cod10=(\w+)`,
    productIdPattern: String.raw`cod10=(\w+)`,
    tier: "marketplace",
    region: "IT",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "bags", "accessories"],
    access: "partner_api",
    compliance: "partner_agreement",
    lifecycle: "partner_required",
    requiresEnv: ["YNAP_PARTNER_TOKEN"],
    notes: "Grupo YNAP (mismo acuerdo). Pendiente de acuerdo comercial.",
    docsUrl: "https://www.ynap.com/",
  }),
];
