import type { ConnectorSpec } from "../base/types";
import { bespoke, declarative, scaffold } from "./spec";

/**
 * Mercado español (fuera de Inditex/H&M): Mango, grupo Tendam, marcas DTC y
 * grandes almacenes. Es el mercado prioritario de la demo, así que aquí está la
 * mayor densidad de fuentes.
 */

export const SPAIN_SOURCES: ConnectorSpec[] = [
  bespoke({
    id: "mango",
    label: "Mango",
    brand: "Mango",
    group: "Mango",
    homeUrl: "https://shop.mango.com/es",
    sitemapUrls: [
      "https://shop.mango.com/sitemap.xml",
      "https://shop.mango.com/sitemaps/sitemap-es-ES.xml",
    ],
    productUrlPattern: String.raw`shop\.mango\.com\/.+_\d{6,}(\.html)?([?#]|$)`,
    productIdPattern: String.raw`_(\d{6,})(?:\.html)?(?:[?#]|$)`,
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "accessories"],
    verification: "contract",
    notes:
      "Contrato de extracción cubierto por tests (__NEXT_DATA__, precio rebajado vs tachado) contra fixtures SINTÉTICOS, no capturas de la tienda. " +
      "Desde el entorno de desarrollo shop.mango.com devuelve 403 a nivel de IP y no se intenta eludir: " +
      "el estado real es `blocked_or_challenged` hasta poder probarlo desde una red permitida.",
  }),
  declarative({
    id: "desigual",
    label: "Desigual",
    brand: "Desigual",
    homeUrl: "https://www.desigual.com/es_ES/",
    sitemapUrls: ["https://www.desigual.com/sitemap.xml"],
    productUrlPattern: String.raw`desigual\.com\/[a-z]{2}_[A-Z]{2}\/\d{2}[A-Za-z]{3,6}\d{1,2}\.html([?#]|$)`,
    productIdPattern: null,
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "accessories"],
    notes:
      "Salesforce Commerce Cloud con JSON-LD en ficha. Patrón de ficha derivado de la estructura pública de URLs; sin verificar contra la tienda.",
  }),
  declarative({
    id: "bimba-y-lola",
    label: "Bimba y Lola",
    brand: "Bimba y Lola",
    homeUrl: "https://www.bimbaylola.com/es_ES/",
    sitemapUrls: ["https://www.bimbaylola.com/sitemap.xml"],
    productUrlPattern: String.raw`bimbaylola\.com\/.+\/p\/\d+`,
    productIdPattern: String.raw`\/p\/(\d+)`,
    tier: "premium",
    segments: ["women"],
    categories: ["bags", "clothing", "footwear", "accessories"],
    notes:
      "Marca prioritaria para la categoría bolsos/accesorios. Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "scalpers",
    label: "Scalpers",
    brand: "Scalpers",
    homeUrl: "https://scalperscompany.com/",
    sitemapUrls: ["https://scalperscompany.com/sitemap.xml"],
    productUrlPattern: String.raw`scalperscompany\.com\/products\/\d{4,6}-[A-Za-z0-9-]+([?#]|$)`,
    productIdPattern: String.raw`scalperscompany\.com\/products\/(\d{4,6})-`,
    tier: "premium",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "accessories"],
    notes:
      "Shopify: sitemap_products_*.xml y JSON-LD estándar de Shopify. Es la plataforma más predecible del registro.",
  }),
  declarative({
    id: "ecoalf",
    label: "Ecoalf",
    brand: "Ecoalf",
    homeUrl: "https://ecoalf.com/es/",
    sitemapUrls: ["https://ecoalf.com/sitemap.xml"],
    productUrlPattern: String.raw`ecoalf\.com\/.+\/products\/[a-z0-9-]+`,
    productIdPattern: String.raw`\/products\/([a-z0-9-]+)`,
    tier: "premium",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Shopify: sitemap de productos + JSON-LD estándar.",
  }),
  declarative({
    id: "springfield",
    label: "Springfield",
    brand: "Springfield",
    group: "Tendam",
    homeUrl: "https://myspringfield.com/es/",
    sitemapUrls: ["https://myspringfield.com/sitemap.xml"],
    productUrlPattern: String.raw`myspringfield\.com\/.+\/p\/\d+`,
    productIdPattern: String.raw`\/p\/(\d+)`,
    segments: ["women", "men"],
    categories: ["clothing", "footwear"],
    notes: "Plataforma Tendam. Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "cortefiel",
    label: "Cortefiel",
    brand: "Cortefiel",
    group: "Tendam",
    homeUrl: "https://cortefiel.com/es/",
    sitemapUrls: ["https://cortefiel.com/sitemap.xml"],
    productUrlPattern: String.raw`cortefiel\.com\/.+\/p\/\d+`,
    productIdPattern: String.raw`\/p\/(\d+)`,
    tier: "premium",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Plataforma Tendam. Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "women-secret",
    label: "Women'secret",
    brand: "Women'secret",
    group: "Tendam",
    homeUrl: "https://womensecret.com/es/",
    sitemapUrls: ["https://womensecret.com/sitemap.xml"],
    productUrlPattern: String.raw`womensecret\.com\/.+\/p\/\d+`,
    productIdPattern: String.raw`\/p\/(\d+)`,
    segments: ["women"],
    categories: ["clothing", "lingerie", "swimwear"],
    notes: "Plataforma Tendam. Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "pedro-del-hierro",
    label: "Pedro del Hierro",
    brand: "Pedro del Hierro",
    group: "Tendam",
    homeUrl: "https://pedrodelhierro.com/es/",
    sitemapUrls: ["https://pedrodelhierro.com/sitemap.xml"],
    productUrlPattern: String.raw`pedrodelhierro\.com\/.+\/p\/\d+`,
    productIdPattern: String.raw`\/p\/(\d+)`,
    tier: "premium",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Plataforma Tendam. Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "adolfo-dominguez",
    label: "Adolfo Domínguez",
    brand: "Adolfo Domínguez",
    homeUrl: "https://www.adolfodominguez.com/es-es/",
    sitemapUrls: ["https://www.adolfodominguez.com/sitemap.xml"],
    productUrlPattern: String.raw`adolfodominguez\.com\/.+\/[A-Za-z][A-Za-z_-]*-\d{10,14}\.html([?#]|$)`,
    productIdPattern: String.raw`adolfodominguez\.com\/.+-(\d{10,14})\.html`,
    tier: "premium",
    segments: ["women", "men"],
    categories: ["clothing", "footwear", "accessories"],
    notes: "Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "camper",
    label: "Camper",
    brand: "Camper",
    homeUrl: "https://www.camper.com/es_ES",
    sitemapUrls: ["https://www.camper.com/sitemap.xml"],
    productUrlPattern: String.raw`camper\.com\/[a-z]{2}_[A-Z]{2}\/.+\/[A-Za-z][A-Za-z_-]*\d{3,6}-\d{3}([?#]|$)`,
    productIdPattern: String.raw`camper\.com\/.+\/[A-Za-z_-]*?([A-Z]?\d{5,6}-\d{3})([?#]|$)`,
    tier: "premium",
    segments: ["women", "men", "kids"],
    categories: ["footwear", "bags"],
    notes:
      "Referencia clave para la categoría calzado. Patrón de ficha sin verificar contra la tienda.",
  }),
  declarative({
    id: "parfois",
    label: "Parfois",
    brand: "Parfois",
    homeUrl: "https://www.parfois.com/es/es/",
    sitemapUrls: ["https://www.parfois.com/sitemap.xml"],
    productUrlPattern: String.raw`parfois\.com\/.+\/\d{6,}[_-]\w+\.html`,
    productIdPattern: String.raw`\/(\d{6,})[_-]`,
    segments: ["women"],
    categories: ["bags", "accessories", "jewelry"],
    notes:
      "Cubre bolsos/accesorios/bisutería, categorías que el analizador detecta con frecuencia. Sin verificar.",
  }),
  declarative({
    id: "tous",
    label: "TOUS",
    brand: "TOUS",
    homeUrl: "https://www.tous.com/es-es/",
    sitemapUrls: ["https://www.tous.com/sitemap.xml"],
    productUrlPattern: String.raw`tous\.com\/.+\/p\/\d+`,
    productIdPattern: String.raw`\/p\/(\d+)`,
    tier: "premium",
    segments: ["women"],
    categories: ["jewelry", "watches", "bags"],
    notes:
      "Cubre joyería/relojes, categorías del selector del analizador. Patrón sin verificar.",
  }),
  scaffold({
    id: "el-corte-ingles",
    label: "El Corte Inglés (moda)",
    brand: "El Corte Inglés",
    homeUrl: "https://www.elcorteingles.es/moda/",
    productUrlPattern: String.raw`elcorteingles\.es\/.+\/\d{10,}-`,
    productIdPattern: String.raw`\/(\d{10,})-`,
    tier: "department_store",
    segments: ["women", "men", "kids"],
    categories: ["clothing", "footwear", "accessories", "home"],
    access: "affiliate_feed",
    compliance: "affiliate_agreement",
    lifecycle: "partner_required",
    notes:
      "Multimarca con anti-bot agresivo. Vía legítima: feed de producto del programa de afiliación (Awin). Pendiente de alta aprobada; no se ingiere nada hasta entonces.",
    docsUrl: "https://www.awin.com/es/anunciantes",
  }),
];
